server:
  port: 8083
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fethRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka